PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZTESTUDO_PRODUTO-IDPRODUTO .
    FIELD ZTESTUDO_PRODUTO-IDFORNEC .
    FIELD ZTESTUDO_PRODUTO-DESCRICAO .
    FIELD ZTESTUDO_PRODUTO-TIPO_EMBALAGEM .
    FIELD ZTESTUDO_PRODUTO-EMBALAGEM .
    FIELD ZTESTUDO_PRODUTO-PRECO .
    FIELD ZTESTUDO_PRODUTO-QUANTIDADE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZTESTUDO_PRODUTO-IDPRODUTO .
    FIELD ZTESTUDO_PRODUTO-IDFORNEC .
  module detail_pai.
 endchain.
