PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZTESTUDO_FORNEC-IDFORNEC .
    FIELD ZTESTUDO_FORNEC-RAZAO_SOCIAL .
    FIELD ZTESTUDO_FORNEC-ESTADO .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZTESTUDO_FORNEC-IDFORNEC .
  module detail_pai.
 endchain.
